"""autogenerated by genpy from tactilesensors/StaticData.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import tactilesensors.msg

class StaticData(genpy.Message):
  _md5sum = "2e63c89b32d4a018cbcdfb283a9e102a"
  _type = "tactilesensors/StaticData"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8 SensorID
Array1d Data

================================================================================
MSG: tactilesensors/Array1d
int32[12] thedata

"""
  __slots__ = ['SensorID','Data']
  _slot_types = ['uint8','tactilesensors/Array1d']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       SensorID,Data

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(StaticData, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.SensorID is None:
        self.SensorID = 0
      if self.Data is None:
        self.Data = tactilesensors.msg.Array1d()
    else:
      self.SensorID = 0
      self.Data = tactilesensors.msg.Array1d()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_struct_B.pack(self.SensorID))
      buff.write(_struct_12i.pack(*self.Data.thedata))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.Data is None:
        self.Data = tactilesensors.msg.Array1d()
      end = 0
      start = end
      end += 1
      (self.SensorID,) = _struct_B.unpack(str[start:end])
      start = end
      end += 48
      self.Data.thedata = _struct_12i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_struct_B.pack(self.SensorID))
      buff.write(self.Data.thedata.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.Data is None:
        self.Data = tactilesensors.msg.Array1d()
      end = 0
      start = end
      end += 1
      (self.SensorID,) = _struct_B.unpack(str[start:end])
      start = end
      end += 48
      self.Data.thedata = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=12)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_12i = struct.Struct("<12i")
_struct_B = struct.Struct("<B")
