/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/longfei/catkin_ws/src/youbot/youbot_modbus_server/srv/YoubotModbusSensorMsg.srv
 *
 */


#ifndef YOUBOT_MODBUS_SERVER_MESSAGE_YOUBOTMODBUSSENSORMSGRESPONSE_H
#define YOUBOT_MODBUS_SERVER_MESSAGE_YOUBOTMODBUSSENSORMSGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace youbot_modbus_server
{
template <class ContainerAllocator>
struct YoubotModbusSensorMsgResponse_
{
  typedef YoubotModbusSensorMsgResponse_<ContainerAllocator> Type;

  YoubotModbusSensorMsgResponse_()
    : header()
    , data_validity(false)
    , station_1_status(0)
    , station_2_status(0)
    , station_3_status(0)
    , station_4_status(0)
    , station_5_status(0)
    , station_6_status(0)  {
    }
  YoubotModbusSensorMsgResponse_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data_validity(false)
    , station_1_status(0)
    , station_2_status(0)
    , station_3_status(0)
    , station_4_status(0)
    , station_5_status(0)
    , station_6_status(0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _data_validity_type;
  _data_validity_type data_validity;

   typedef int8_t _station_1_status_type;
  _station_1_status_type station_1_status;

   typedef int8_t _station_2_status_type;
  _station_2_status_type station_2_status;

   typedef int8_t _station_3_status_type;
  _station_3_status_type station_3_status;

   typedef int8_t _station_4_status_type;
  _station_4_status_type station_4_status;

   typedef int8_t _station_5_status_type;
  _station_5_status_type station_5_status;

   typedef int8_t _station_6_status_type;
  _station_6_status_type station_6_status;




  typedef boost::shared_ptr< ::youbot_modbus_server::YoubotModbusSensorMsgResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::youbot_modbus_server::YoubotModbusSensorMsgResponse_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct YoubotModbusSensorMsgResponse_

typedef ::youbot_modbus_server::YoubotModbusSensorMsgResponse_<std::allocator<void> > YoubotModbusSensorMsgResponse;

typedef boost::shared_ptr< ::youbot_modbus_server::YoubotModbusSensorMsgResponse > YoubotModbusSensorMsgResponsePtr;
typedef boost::shared_ptr< ::youbot_modbus_server::YoubotModbusSensorMsgResponse const> YoubotModbusSensorMsgResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::youbot_modbus_server::YoubotModbusSensorMsgResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::youbot_modbus_server::YoubotModbusSensorMsgResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace youbot_modbus_server

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::youbot_modbus_server::YoubotModbusSensorMsgResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::youbot_modbus_server::YoubotModbusSensorMsgResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::youbot_modbus_server::YoubotModbusSensorMsgResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::youbot_modbus_server::YoubotModbusSensorMsgResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::youbot_modbus_server::YoubotModbusSensorMsgResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::youbot_modbus_server::YoubotModbusSensorMsgResponse_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::youbot_modbus_server::YoubotModbusSensorMsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e967a875de4051ba529fb5f81fc9d2d6";
  }

  static const char* value(const ::youbot_modbus_server::YoubotModbusSensorMsgResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe967a875de4051baULL;
  static const uint64_t static_value2 = 0x529fb5f81fc9d2d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::youbot_modbus_server::YoubotModbusSensorMsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "youbot_modbus_server/YoubotModbusSensorMsgResponse";
  }

  static const char* value(const ::youbot_modbus_server::YoubotModbusSensorMsgResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::youbot_modbus_server::YoubotModbusSensorMsgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
bool data_validity\n\
int8 station_1_status\n\
int8 station_2_status\n\
int8 station_3_status\n\
int8 station_4_status\n\
int8 station_5_status\n\
int8 station_6_status\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::youbot_modbus_server::YoubotModbusSensorMsgResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::youbot_modbus_server::YoubotModbusSensorMsgResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data_validity);
      stream.next(m.station_1_status);
      stream.next(m.station_2_status);
      stream.next(m.station_3_status);
      stream.next(m.station_4_status);
      stream.next(m.station_5_status);
      stream.next(m.station_6_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct YoubotModbusSensorMsgResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::youbot_modbus_server::YoubotModbusSensorMsgResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::youbot_modbus_server::YoubotModbusSensorMsgResponse_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data_validity: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.data_validity);
    s << indent << "station_1_status: ";
    Printer<int8_t>::stream(s, indent + "  ", v.station_1_status);
    s << indent << "station_2_status: ";
    Printer<int8_t>::stream(s, indent + "  ", v.station_2_status);
    s << indent << "station_3_status: ";
    Printer<int8_t>::stream(s, indent + "  ", v.station_3_status);
    s << indent << "station_4_status: ";
    Printer<int8_t>::stream(s, indent + "  ", v.station_4_status);
    s << indent << "station_5_status: ";
    Printer<int8_t>::stream(s, indent + "  ", v.station_5_status);
    s << indent << "station_6_status: ";
    Printer<int8_t>::stream(s, indent + "  ", v.station_6_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOUBOT_MODBUS_SERVER_MESSAGE_YOUBOTMODBUSSENSORMSGRESPONSE_H
