/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/longfei/catkin_ws/src/tactilesensors/msg/StaticData.msg
 *
 */


#ifndef TACTILESENSORS_MESSAGE_STATICDATA_H
#define TACTILESENSORS_MESSAGE_STATICDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <tactilesensors/Array1d.h>

namespace tactilesensors
{
template <class ContainerAllocator>
struct StaticData_
{
  typedef StaticData_<ContainerAllocator> Type;

  StaticData_()
    : SensorID(0)
    , Data()  {
    }
  StaticData_(const ContainerAllocator& _alloc)
    : SensorID(0)
    , Data(_alloc)  {
    }



   typedef uint8_t _SensorID_type;
  _SensorID_type SensorID;

   typedef  ::tactilesensors::Array1d_<ContainerAllocator>  _Data_type;
  _Data_type Data;




  typedef boost::shared_ptr< ::tactilesensors::StaticData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tactilesensors::StaticData_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct StaticData_

typedef ::tactilesensors::StaticData_<std::allocator<void> > StaticData;

typedef boost::shared_ptr< ::tactilesensors::StaticData > StaticDataPtr;
typedef boost::shared_ptr< ::tactilesensors::StaticData const> StaticDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tactilesensors::StaticData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tactilesensors::StaticData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tactilesensors

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'tactilesensors': ['/home/longfei/catkin_ws/src/tactilesensors/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tactilesensors::StaticData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tactilesensors::StaticData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tactilesensors::StaticData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tactilesensors::StaticData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tactilesensors::StaticData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tactilesensors::StaticData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tactilesensors::StaticData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2e63c89b32d4a018cbcdfb283a9e102a";
  }

  static const char* value(const ::tactilesensors::StaticData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2e63c89b32d4a018ULL;
  static const uint64_t static_value2 = 0xcbcdfb283a9e102aULL;
};

template<class ContainerAllocator>
struct DataType< ::tactilesensors::StaticData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tactilesensors/StaticData";
  }

  static const char* value(const ::tactilesensors::StaticData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tactilesensors::StaticData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 SensorID\n\
Array1d Data\n\
\n\
================================================================================\n\
MSG: tactilesensors/Array1d\n\
int32[12] thedata\n\
";
  }

  static const char* value(const ::tactilesensors::StaticData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tactilesensors::StaticData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.SensorID);
      stream.next(m.Data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct StaticData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tactilesensors::StaticData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tactilesensors::StaticData_<ContainerAllocator>& v)
  {
    s << indent << "SensorID: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.SensorID);
    s << indent << "Data: ";
    s << std::endl;
    Printer< ::tactilesensors::Array1d_<ContainerAllocator> >::stream(s, indent + "  ", v.Data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TACTILESENSORS_MESSAGE_STATICDATA_H
