(cl:defpackage ur_msgs-srv
  (:use )
  (:export
   "GRIPPERMOVE"
   "<GRIPPERMOVE-REQUEST>"
   "GRIPPERMOVE-REQUEST"
   "<GRIPPERMOVE-RESPONSE>"
   "GRIPPERMOVE-RESPONSE"
   "SETPAYLOAD"
   "<SETPAYLOAD-REQUEST>"
   "SETPAYLOAD-REQUEST"
   "<SETPAYLOAD-RESPONSE>"
   "SETPAYLOAD-RESPONSE"
   "SETIO"
   "<SETIO-REQUEST>"
   "SETIO-REQUEST"
   "<SETIO-RESPONSE>"
   "SETIO-RESPONSE"
  ))

