(cl:in-package youbot_modbus_server-srv)
(cl:export '(HEADER-VAL
          HEADER
          HEADER-VAL
          HEADER
          DATA_VALIDITY-VAL
          DATA_VALIDITY
          ESTOP_BUTTON_STATUS-VAL
          ESTOP_BUTTON_STATUS
          ESTOP_INDICATOR_STATUS-VAL
          ESTOP_INDICATOR_STATUS
          YELLOW_BUTTON_STATUS-VAL
          YELLOW_BUTTON_STATUS
          YELLOW_INDICATOR_STATUS-VAL
          YELLOW_INDICATOR_STATUS
          GREEN_BUTTON_STATUS-VAL
          GREEN_BUTTON_STATUS
          GREEN_INDICATOR_STATUS-VAL
          GREEN_INDICATOR_STATUS
          RUNSTOP_SWITCH_STATUS-VAL
          RUNSTOP_SWITCH_STATUS
          RUNSTOP_INDICATOR_STATUS-VAL
          RUNSTOP_INDICATOR_STATUS
          SUPERVISOR_RUNSTOP_STATUS-VAL
          SUPERVISOR_RUNSTOP_STATUS
))